[package]
name = "latency-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19", features = ["full"]}
log = "0.4"
anyhow = "1.0"
once_cell = "1.12"
thiserror = "1.0.44"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
